default: &default
  num: 5
  ratio: [ 0.2, 0.4, 0.4 ]
  pool: 'map_pool.yaml'
  seeds:
    - 12345
    - 23456
    - 34567

cog2021:
  <<: *default
  seeds:
    - 4534125834 # CUNYbot
    - 87 # Stardust
    - 15 # McRave
    - 37 # BananaBrain
    - 777 # Granite
    - 7777 # Microwave
