default: &default
  num: 5
  ratio: [ 0.2, 0.4, 0.4 ]
  pool: 'map_pool.yaml'
  seeds:
    example_1: 12345
    example_2: 23456
    example_3: 34567

cog2021:
  <<: *default
  seeds:
    CUNYbot:      4534125834
    Stardust:     87
    McRave:       15
    BananaBrain:  37
    Granite:      777
    Microwave:    7777
